### PR TITLE
initialise expected params

### LINKED ISSUE #26: Example config and/or make sure all plugin params are treated as expected
It was relatively easy to get the plugin up and running, but I got a bunch of NF warnings about access to undefined params, for params the plugin used (e.g. `help`).  I thought it would be easy to resolve this, but it was more confusing and time consuming that I thought.

What I ended up with is the following in my config:

```nextflow 
params.schema_ignore_params = "help,monochrome_logs,validationLenientMode,validationFailUnrecognisedParams"
params.monochrome_logs = false
params.help = false
params.validationLenientMode = true
params.validationFailUnrecognisedParams = false
```

Originally I had thought that `schema_ignore_params` took a list, e.g.:

```nextflow 
params.schema_ignore_params =["help" ,"monochrome_logs", "validationLenientMode","validationFailUnrecognisedParams"]
```

However, when I did that I got cryptic error messages on the console like:

```groovy
org.json.JSONException: JSONObject["help"] not found.
```

Digging in the NF log file I found:

```groovy
org.json.JSONException: JSONObject["help"] not found.
        at org.json.JSONObject.get(JSONObject.java:587)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1956)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3843)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:199)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:421)
        at nextflow.validation.SchemaValidator.validateParameters(SchemaValidator.groovy:206)
        at nextflow.validation.SchemaValidator.validateParameters(SchemaValidator.groovy)
        ...
```

It looks to me like in SchemaValidator that it should also add `help` and `monochrome_logs` to the set of `expectedParams`?

I think it would also be helpful to have an example config snipped like the above in the README, and/or make it clear that `schema_ignore_params` is intended to be a CSV string.

### PR DESCRIPTION
**Pull request by mirpedrol**
Close #26

### CODE REVIEW

File: plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy [hunk 1]
```diff
@@ -194,14 +194,52 @@ class SchemaValidator extends PluginExtensionPoint {
...
+        if( !params.containsKey("help") ) {
+            params.help = false
+        }
+        if( !params.containsKey("validationShowHiddenParams") ) {
+            params.validationShowHiddenParams = false
+        }
+        if( !params.containsKey("schema_ignore_params") ) {
+            params.schema_ignore_params = false
+        }
+
```
Comment (nvnieuwk) [inline plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy:220]: Can you add `immutable_meta` with a default of true here too?

**Review by nvnieuwk — APPROVED** [review]

File: plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy (hunk 1 above)
Comment (mirpedrol) [reply plugins/nf-validation/src/main/nextflow/validation/SchemaValidator.groovy:220]: Should we add it in camelCase like the others? I would suggest `validationImmutableMeta`
(I refactored `schema_ignore_params` too in a different PR)
